version: '3.8'
services:
  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env_example
    ports:
      - 5432:5432

  server:
    build: .
    env_file:
      - .env_example
    ports:
      - 5000:5000
    depends_on:
      - db
volumes:
    postgres_data: